### PR TITLE
Migrate code formatting to prettier

### LINKED ISSUE #89: Migrate to prettier
Most of the EMF.cloud projects (including jsonForms and GLSP) are using  a combination of prettier and eslint for linting and formatting.
This works pretty well and is more or less the de facto standard approach. However, the modelserver-theia project uses a custom formatting approach which is incompatible with prettier. In order to not break formatting prettier has to be explicitly disabled. We should unify this formatting settings and also migrate to prettier.

### PR DESCRIPTION
**Pull request by eneufeld**
The project was still using an outdated set of formatting and linting
rules. This is now updated.
In order to unify file headers, mentions of contributions in the file
header was moved to the package.json.

Fix #89

### CODE REVIEW

**Comment by eneufeld** [comment]
@vhemery I had to change the headers of some files that you initially created as I didn't manage to adapt the eslint rule for the header to cope with them. I added you as a contributor to the package.json contributors section instead. Is this fine with you?

**Comment by vhemery** [comment]
> @vhemery I had to change the headers of some files that you initially created as I didn't manage to adapt the eslint rule for the header to cope with them. I added you as a contributor to the package.json contributors section instead. Is this fine with you?

Not to worry. Fine by me.

**Comment by tortmayr** [comment]
@eneufeld  The build is failing because the `theia/blueprint` docker image uses a node version that is to old for the eslint plugin. In other projects we had similar issues and since there is no other ready-to-go theia docker image we decided to simply ignore the engine with `yarn install --ignore-engines` for now. Since security support for node 12 is ending in April I'd expect that the theia/blueprint image will get updated soon and the we can remove the workaround

**Comment by eneufeld** [comment]
updating more stuff finally fixed the build ...

**Review by ndoschek — APPROVED** [review]
Thanks Eugen, looks great to me! :+1:

**Pull request merged**
